# https://www.playframework.com/documentation/latest/Configuration
play.filters.disabled += play.filters.csrf.CSRFFilter
play.filters.enabled += "play.filters.cors.CORSFilter"
play.filters.cors {
  allowedOrigins = [${?CLIENT_URL}]
  allowedMethods = ["GET", "POST", "PUT", "DELETE"]
  allowedHeaders = ["*"]
}
play.filters.hosts.allowed = ["localhost", "127.0.0.1", ${?API_URL}]

play.assets.cache = {
  "Cache-Control" = "public, max-age=31536000"
}

play.modules.enabled += "modules.SecurityModule"

# Required for Pac4j to work with Play 3
# play.modules.enabled += "org.pac4j.play.modules.SecurityModule"

socketService.url=${?SOCKET_SERVICE_URL}
api.url=${?API_URL}
client.url=${?CLIENT_URL}

play.http.secret.key=${?APPLICATION_SECRET}

jwt.secret= = "abcdefg"

# Github OAuth
github.clientId=${?GITHUB_CLIENT_ID}
github.secret=${?GITHUB_CLIENT_SECRET}

# Google OAuth
google.clientId=${?GOOGLE_CLIENT_ID}
google.secret=${?GOOGLE_CLIENT_SECRET}